// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBg4mHvWjEH-HD8c8L3AT0B6ZMkWuYOKE',
    appId: '1:26529754310:web:8a602b45e0e5599d427bc7',
    messagingSenderId: '26529754310',
    projectId: 'vishwakarama-steel',
    authDomain: 'vishwakarama-steel.firebaseapp.com',
    storageBucket: 'vishwakarama-steel.appspot.com',
    measurementId: 'G-EDEYD2107Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD78V18XE8cW_lECrnGduU2XO-zoTDffS4',
    appId: '1:26529754310:android:4d47a603c24a0a40427bc7',
    messagingSenderId: '26529754310',
    projectId: 'vishwakarama-steel',
    storageBucket: 'vishwakarama-steel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyQ-ZS9Hnkc02pBcEyNhcVMd6-T3vD_2o',
    appId: '1:26529754310:ios:7a5503499d77406a427bc7',
    messagingSenderId: '26529754310',
    projectId: 'vishwakarama-steel',
    storageBucket: 'vishwakarama-steel.appspot.com',
    iosBundleId: 'com.example.blockTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyQ-ZS9Hnkc02pBcEyNhcVMd6-T3vD_2o',
    appId: '1:26529754310:ios:7a5503499d77406a427bc7',
    messagingSenderId: '26529754310',
    projectId: 'vishwakarama-steel',
    storageBucket: 'vishwakarama-steel.appspot.com',
    iosBundleId: 'com.example.blockTesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBg4mHvWjEH-HD8c8L3AT0B6ZMkWuYOKE',
    appId: '1:26529754310:web:34a3bbf71d8896e6427bc7',
    messagingSenderId: '26529754310',
    projectId: 'vishwakarama-steel',
    authDomain: 'vishwakarama-steel.firebaseapp.com',
    storageBucket: 'vishwakarama-steel.appspot.com',
    measurementId: 'G-JQPPYQ3429',
  );
}
